# Copy this to .streamlit/secrets.toml and update with your values
# For Streamlit Cloud, add these in the dashboard secrets section

# AWS Configuration
AWS_REGION = "us-east-2"
S3_BUCKET_NAME = "your-bucket-name"
AWS_ACCESS_KEY_ID = "your-access-key"
AWS_SECRET_ACCESS_KEY = "your-secret-key"

# Authentication Configuration
[auth]
cookie_name = "coursera_auth"
cookie_key = "your-random-cookie-key"
cookie_expiry_days = 30

[auth.credentials]
usernames = ["admin", "demo_user"]

[auth.credentials.admin]
email = "admin@example.com"
name = "Administrator"
password = "$2b$12$yourhashhere"  # Use generate_password_hash.py to create

[auth.credentials.demo_user]
email = "demo@example.com"
name = "Demo User"
password = "$2b$12$yourhashhere"  # Use generate_password_hash.py to create 